services:
  postgres:
    image: postgres:16-alpine
    container_name: finpay-postgres
    environment:
      POSTGRES_USER: finpay
      POSTGRES_PASSWORD: finpay
      POSTGRES_DB: finpay
    ports:
      - "5432:5432"
    volumes:
      - finpay-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: finpay-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: finpay-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: finpay-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  finpay-postgres-data:
